// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    App: typeof import('./App.vue')['default']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    HomePage: typeof import('./views/HomePage.vue')['default']
    Login: typeof import('./views/login/index.vue')['default']
    Main: typeof import('./views/main/index.vue')['default']
    Register: typeof import('./views/register/index.vue')['default']
    RegisterLogin: typeof import('./views/RegisterLogin.vue')['default']
    Resigter: typeof import('./components/RegisterLogin/Resigter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Views: typeof import('./views/index.vue')['default']
    Welcome: typeof import('./views/welcome/index.vue')['default']
  }
}
